FROM --platform=$TARGETPLATFORM alpine:3.15.0

ARG TARGETARCH
ARG TARGETPLATFORM
ARG TARGETVARIANT

ARG BASH_VERSION="5.1.8-r0" \
ARG CA_CERTIFICATES_VERSION="20191127-r7" \
ARG CURL_VERSION="7.80.0-r0" \
ARG PROCPS_VERSION="3.3.17-r0" \
ARG RCLONE_VERSION="1.57.0-r1" \
ARG TZDATA_VERSION="2021e-r0"

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN apk add --no-cache \
      bash="${BASH_VERSION}" \
      ca-certificates="${CA_CERTIFICATES_VERSION}" \
      curl="${CURL_VERSION}" \
      procps="${PROCPS_VERSION}" \
      rclone="${RCLONE_VERSION}" \
      tzdata="${TZDATA_VERSION}"

ARG SUPERCRONIC_VERSION=v0.1.12
ARG SUPERCRONIC_URL="https://github.com/aptible/supercronic/releases/download/${SUPERCRONIC_VERSION}/supercronic-linux-${TARGETARCH}" \
ARG SUPERCRONIC="supercronic-linux-${TARGETARCH}" \
ARG SUPERCRONIC_SHA1SUM="SUPERCRONIC_SHA1SUM_${TARGETARCH}" \
ARG SUPERCRONIC_SHA1SUM_amd64="048b95b48b708983effb2e5c935a1ef8483d9e3e" \
ARG SUPERCRONIC_SHA1SUM_arm64="8baba3dd0b0b13552aca179f6ef10d55e5dee28b" \
ARG SUPERCRONIC_SHA1SUM_arm="d72d3d40065c0188b3f1a0e38fe6fecaa098aad5"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN curl -fsSLO "${SUPERCRONIC_URL}" \
 && echo "${!SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
 && chmod +x "${SUPERCRONIC}" \
 && mv "${SUPERCRONIC}" "/usr/local/bin/${SUPERCRONIC}" \
 && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic

RUN mkdir /data /conf \
 && chown 1000:1000 /data /conf
COPY crontab /conf/crontab

USER 1000

WORKDIR /data
ENV XDG_CONFIG_HOME=/conf

CMD /usr/local/bin/supercronic /conf/crontab

ARG CREATED
ARG REVISION=HEAD

LABEL org.opencontainers.image.authors="https://github.com/cewood" \
      org.opencontainers.image.created="${CREATED}" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.revision="${REVISION}" \
      org.opencontainers.image.source="https://github.com/cewood/supercronic-docker/tree/${REVISION}" \
      org.opencontainers.image.title="cewood/supercronic" \
      org.opencontainers.image.url="https://github.com/cewood/supercronic-docker"
