name: main

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Set up Qemu for Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # Set up Buildx for Docker
    - name: Set up Buildx for Docker
      uses: docker/setup-buildx-action@v1

    # Login to Docker Hub
    - name: Login to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build images
    - name: Build images
      run: make ci
